@uri=http://localhost:4000/
###
GET {{uri}}
### 
GET  {{uri}}products

###
POST {{uri}}products
Content-Type: application/json

{
  "title":"产品4"
}

### 

PUT {{uri}}products/5f2b94f05ffd270cd2437cef
Content-Type: application/json

{
  "title":"产品8"
}
